recipeWebsite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name = 'detail'),
    path('login/', views.Login, name = 'login'),
    path('auth/', views.Auth, name= 'auth'),
    path('logout/', views.log_out, name = 'logout'),
    path('register/', views.Register, name='register'),
    path('createuser/', views.create_user, name= 'createuser'),
    path('changepassword/', views.change_password, name='changepassword'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('profile/addrecipe/', views.AddView.as_view(), name='add'),
]

recipeWebsite/recipeWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

recipeWebsite/blog/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User


class Topic(models.Model):
    topic = models.CharField(max_length = 200)
    
    def __str__(self):
        return self.topic

class Recipe(models.Model):
    recipe_name = models.CharField(max_length= 200)
    pub_date = models.DateTimeField('date published')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    #recipe_picture = models.ImageField(upload_to = '', default= '')

    def __str__(self):
        return self.recipe_name

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=30) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Ingredient(models.Model):
    #topic = models.ForeignKey(Topic, on_delete= models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete= models.CASCADE)
    ingredient_name = models.CharField(max_length=300)
    ingredient_amount = models.CharField(max_length= 60)

    def __str__(self):
        return self.ingredient_name

class Instruction(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete= models.CASCADE)
    instruction_step = models.CharField(max_length= 1000)

    def __str__(self):
        return self.instruction_step

recipeWebsite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Recipe, Ingredient, Instruction
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.db.utils import IntegrityError
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.core.exceptions import PermissionDenied

class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_recipe_list'

    def get_queryset(self):
        return Recipe.objects.order_by('-pub_date')[:10]

class DetailView(generic.DetailView):
    template_name = 'blog/detail.html'
    model = Recipe

def Register(request, error_message=None):
    return render(request, 'blog/register.html')

def create_user(request):
    username = request.POST['username']
    password = request.POST['password']
    email = request.POST['email']
    try: 
        User.objects.create_user(username, email, password)
        user = authenticate(request, username=username, password=password)
        login(request,user)
        return HttpResponseRedirect(reverse('blog:index'))
    except IntegrityError:
        messages.error(request, "Username is already taken :(")#Try the xml chek username in realtime
        return HttpResponseRedirect(reverse('blog:register'))

def Auth(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request,user)
        #Redirect to a home page
        return HttpResponseRedirect(reverse('blog:index'))
    else:
        #Send an error message
        messages.error(request, "Username or Password incorrect/invalid")
        return HttpResponseRedirect(reverse('blog:login'))

def Login(request):
    return render(request, 'blog/login.html')
        
def log_out(request):
    logout(request)
    #Redirect to a login page
    return HttpResponseRedirect(reverse('blog:login'))

def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Password updated successfully")
        else:
            messages.error(request, "Please correct the error below")
    return HttpResponseRedirect(reverse('blog:profile'))

class ProfileView(LoginRequiredMixin, generic.ListView):
    redirect_field_name =""
    template_name = 'blog/profile.html'
    model = Recipe
    context_object_name='my_recipe_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = PasswordChangeForm(self.request.user)
        return context

    def get_queryset(self):
        return Recipe.objects.filter(author__username=self.request.user.username)

class EditView(LoginRequiredMixin, generic.DetailView):
    redirect_field_name =""
    template_name='blog/edit.html'
    model = Recipe
    
    def get_queryset(self):
        query = super(EditView, self).get_queryset()
        return query.filter(author=self.request.user)


    def post(self, request, pk):
        if request.POST['op'] == "delete":
            recipe = get_object_or_404(Recipe, pk=pk)
            recipe.delete()
            return HttpResponseRedirect(reverse('blog:profile'))
        read_recipe_form(request, request.POST, id=pk)
        messages.info(request, "Recipe updated!")
        return HttpResponseRedirect(reverse('blog:edit', args=(pk,)))
    

class AddView(LoginRequiredMixin, generic.View):
    redirect_field_name=""
    template_name = 'blog/add.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        read_recipe_form(request, request.POST, id=None)
        messages.info(request, "Recipe saved!")
        return HttpResponseRedirect(reverse('blog:profile'))


def read_recipe_form(request, form, id=None):
    if id is not None:
        recipe = get_object_or_404(Recipe, pk=id)
        recipe.ingredient_set.all().delete() #Delete then replace with new one
        recipe.instruction_set.all().delete()
    else:
        recipe = Recipe(author = request.user, pub_date=timezone.now())

    current = None

    for item in form: #request.POST --> dictionary

        if item == "recipe_name":
            recipe.recipe_name = form[item]
            recipe.save()

        elif item.startswith("ingredient_name"):
            ingredient = Ingredient(ingredient_name = form[item], ingredient_amount="",recipe=recipe)
            current = ingredient

        elif item.startswith("ingredient_amount"):
            ingredient=current
            ingredient.ingredient_amount = form[item]
            ingredient.save()

        elif item.startswith("instruction"):
            instruction = Instruction(instruction_step=form[item], recipe = recipe)
            instruction.save()
    return 

        

recipeWebsite/blog/templates/blog/add.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}ADD NEW RECIPE{% endblock %}

{% block content %}
<script>
    let countIng = 1;
    let countIns = 1;
</script>

<form action = "{% url 'blog:add' %}" method = "POST">
    {% csrf_token %}

<h3>Name of your recipe</h3>
<input type="text" name = "recipe_name" id = "recipe_name" required>

<h3>Ingredient</h3>
<table>
    <tr>
        <th>Ingredient</th><th>Amount</th>
    </tr>
    <tr id="row1">
        <td><input type = "text" name = "ingredient_name1" id = "ingredient_name1" required></li> </td>
        <td><input type = "text" name = "ingredient_amount1" id = "ingredient_amount1" required></td>
        <td><button type="button" id="delete1">Delete</button>
        <script>document.getElementById("delete1").addEventListener('click',evt=>{
            document.getElementById("row1").remove();});</script></td>
    </tr>


    <tr id="addRowIng"><td><button type="button" id = "addIng">Add item</button></td></tr>
    <script>
        countIng += 1;
        const addIng = document.getElementById("addIng");
        const addRowIng = document.getElementById("addRowIng");
        addIng.addEventListener('click', evt=>{
            const count=countIng;
            let newRow = document.createElement('tr');
            newRow.innerHTML= `<td><input type = "text" name = "ingredient_name${count}" id = "ingredient_name${count}"></li> </td>`;
            newRow.innerHTML += `<td><input type = "text" name = "ingredient_amount${count} id = "ingredient_amount${count}"></td>`;
            newRow.innerHTML += `<td><button type="button" id="delete${count}">Delete</button>`;
            newRow.setAttribute('id', `row${count}`);
            addRowIng.before(newRow);
            document.querySelector(`#delete${count}`).addEventListener('click', evt=>{
                document.getElementById(`row${count}`).remove()});
            countIng+=1;
        });
    </script>
</table>

<h3>Instructions</h3>

<table>
    <tr>
        <th>Steps</th>
    </tr>
    <tr id="rowIns1">
        <td><textarea name = "instruction1"
        id = "instruction1" cols="50" rows="4"></textarea></td>
        <td><button type="button" id="deleteIns1">Delete</button>
        <script>document.getElementById("deleteIns1").addEventListener('click',evt=>{
            document.getElementById("rowIns1").remove();});</script></td>
    </tr>
    
    <tr id="addRowIns"><td><button type="button" id="addIns">Add Item</button></td></tr>
    <script>
        countIns += 1;
        const addIns = document.getElementById("addIns");
        const addRowIns = document.getElementById("addRowIns");
        addIns.addEventListener('click', evt=>{
            const count=countIns;
            let newRow = document.createElement('tr');
            newRow.innerHTML = `<td><textarea name = "instruction${count}"
            id = "instruction${count}" cols="50" rows="4"></textarea></td>`;
            newRow.innerHTML += `<td><button type="button" id="deleteIns${count}">Delete</button>`;
            newRow.setAttribute('id', `row${count}`);
            addRowIns.before(newRow);
            document.querySelector(`#deleteIns${count}`).addEventListener('click', evt=>{
                document.getElementById(`row${count}`).remove();});
            countIns +=1;
        });

    </script>
</table>
<input type="submit" value= "Save changes">
</form>
{% endblock %}

recipeWebsite/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<head>
    <title>{% block title %}MIKO's Recipe{% endblock %}</title>
    <link rel = "stylesheet" type = "text/css" href="{% static 'blog/style.css' %}">
</head>

<body>
    <div class = "navbar">
        {% block navbar %}
        <span id="home">HOME</span>
        <span id="add_recipes">ADD RECIPES</span>
        <span id="my_profile">MY PROFILE</span>
        {% if user.is_authenticated %}
            <span id="logout">Logout</span>
        {% else %}
            <span id="login">Login</span>
        {% endif %}
        {% endblock %}
    </div>

    <div class = "messages">
        {% block messages %}
        {% if messages %}
        <ul class = "messages">
            {% for message in messages %}
            <li {% if message.tags %} class = "{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endblock %}
    </div>
    
    <div class = "content">
        {% block content %}{% endblock %}
    </div>

    <script>
        const home = document.getElementById("home")
        const login = document.getElementById("login")
        const logout = document.getElementById("logout")
        const profile = document.getElementById("my_profile")
        const addRecipe = document.getElementById("add_recipes")
        home.addEventListener('click', evt => {
            window.location.href = "{% url 'blog:index' %}";
        });

        profile.addEventListener('click', evt => {
            window.location.href = "{% url 'blog:profile' %}";
        });

        addRecipe.addEventListener('click', evt=> {
            window.location.href= "{% url 'blog:add' %}";
        });

        if (login){
            login.addEventListener('click', evt => {
                window.location.href = "{% url 'blog:login' %}"
        })}
        else if (logout){
            logout.addEventListener('click', evt=> {
                window.location.href = "{% url 'blog:logout' %}"
            })
        }

    </script>
</body>

recipeWebsite/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}


{% block title %}{{recipe.recipe_name}}{% endblock %}

{% block content %}
<h1 class = "recipe_title">{{recipe.recipe_name}}</h1>
<h2 class = "author">Author: {{ recipe.author }}</h2>
<h2 class = "ingredient_title">Ingredients</h2>
<ul class = "ingredient_list"> <!--unordered list-->
    {% for ingredient in recipe.ingredient_set.all %}
    <li>{{ingredient.ingredient_amount}} {{ingredient.ingredient_name}}</li>
    {% endfor %}    
</ul>
<h2 class = "instruction_title">Instructions</h2>
<ol class = "instruction_list"> <!--ordered list-->
    {% for instruction in recipe.instruction_set.all %}
    <li>{{instruction.instruction_step}}</li>
    {% endfor %}
</ol>
{% endblock %}

recipeWebsite/blog/templates/blog/edit.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Edit {{recipe.recipe_name}}{% endblock %}

{% block content %}
<h1>EDIT RECIPE</h1>
<script>
    let countIng;
    let countIns;
</script>

<form action = "" method = "POST">
    {% csrf_token %}

<input type="submit" name="op" value="delete">

<input type = "hidden" name="id" value="{{recipe.id}}">
<h3>Edit name</h3>
<input type="text" value = "{{recipe.recipe_name}}" name = "recipe_name" id = "recipe_name">
<h3>Ingredient</h3>

<table>
    <tr>
        <th>Ingredient</th><th>Amount</th>
    </tr>
    {% for ingredient in recipe.ingredient_set.all %}
    <tr id="row{{forloop.counter}}">
        <script>countIng=parseInt("{{forloop.counter}}");</script>
        <td><input type = "text" value = "{{ingredient.ingredient_name}}" 
        name = "ingredient_name{{forloop.counter}}" id = "ingredient_name{{forloop.counter}}"></li> </td>
        <td><input type = "text" value = "{{ingredient.ingredient_amount}}"
        name = "ingredient_amount{{forloop.counter}}" id = "ingredient_amount{{forloop.counter}}"></td>
        <td><button type="button" id="delete{{forloop.counter}}">Delete</button>
        <script>document.getElementById("delete{{forloop.counter}}").addEventListener('click',evt=>{
            document.getElementById("row{{forloop.counter}}").remove()});</script></td>
    </tr>
    {% endfor %}

    <tr id="addRowIng"><td><button type="button" id = "addIng">Add item</button></td></tr>
    <script>
        countIng += 1;
        const addIng = document.getElementById("addIng");
        const addRowIng = document.getElementById("addRowIng");
        addIng.addEventListener('click', evt=>{
            const count=countIng;
            let newRow = document.createElement('tr');
            newRow.innerHTML= `<td><input type = "text" name = "ingredient_name${count}" id = "ingredient_name${count}"></li> </td>`;
            newRow.innerHTML += `<td><input type = "text" name = "ingredient_amount${count} id = "ingredient_amount${count}"></td>`;
            newRow.innerHTML += `<td><button type="button" id="delete${count}">Delete</button>`;
            newRow.setAttribute('id', `row${count}`);
            addRowIng.before(newRow);
            document.querySelector(`#delete${count}`).addEventListener('click', evt=>{
                document.getElementById(`row${count}`).remove()});
            countIng+=1;
        });
    </script>
</table>

<h3>Instructions</h3>

<table>
    <tr>
        <th>Steps</th>
    </tr>
    {% for instruction in recipe.instruction_set.all %}
    <tr id="rowIns{{forloop.counter}}">
        <script>countIns=parseInt("{{forloop.counter}}");</script>
        <td><textarea name = "instruction{{forloop.counter}}"
        id = "instruction{{forloop.counter}}" cols="50" rows="4">{{instruction.instruction_step}}</textarea></td>
        <td><button type="button" id="deleteIns{{forloop.counter}}">Delete</button>
        <script>document.getElementById("deleteIns{{forloop.counter}}").addEventListener('click',evt=>{
            document.getElementById("rowIns{{forloop.counter}}").remove();});</script></td>
    </tr>
    {% endfor %}
    <tr id="addRowIns"><td><button type="button" id="addIns">Add Item</button></td></tr>
    <script>
        countIns += 1;
        const addIns = document.getElementById("addIns");
        const addRowIns = document.getElementById("addRowIns");
        addIns.addEventListener('click', evt=>{
            const count=countIns;
            let newRow = document.createElement('tr');
            newRow.innerHTML = `<td><textarea name = "instruction${count}"
            id = "instruction${count}" cols="50" rows="4"></textarea></td>`;
            newRow.innerHTML += `<td><button type="button" id="deleteIns${count}">Delete</button>`;
            newRow.setAttribute('id', `row${count}`);
            addRowIns.before(newRow);
            document.querySelector(`#deleteIns${count}`).addEventListener('click', evt=>{
                document.getElementById(`row${count}`).remove();});
            countIns +=1;
        });

    </script>
</table>
<input type="submit" name = "op" value= "Save changes">
</form>
{% endblock %}

recipeWebsite/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}MIKO's COOKING{% endblock %}

{% block content %}
{% if latest_recipe_list %}
<ul class="recipe_list">
    {% for recipe in latest_recipe_list %}
    <li><a href = "{% url 'blog:detail' recipe.id %}">{{recipe.recipe_name}}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No recipes available :(</p>
{% endif %}
{% endblock %}

recipeWebsite/blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block title %}Login{% endblock %}


{% block content %}
<div class="login">
<form class="form" action ="{% url 'blog:auth' %}" method="POST">
    {% csrf_token %}
    <label for = "username">Username: </label>
    <input type = "text" name = "username" id = "username" placeholder="Username">
    
    <label for = "password">Password: </label>
    <input type = "password" name = "password" id = "password" placeholder="Password">
    
    <input type = "submit" value = "Login">
</form>

<a href = "{% url 'blog:register' %}">Register here</a>
</div>
{% endblock %}

recipeWebsite/blog/templates/blog/profile.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %} MY PROFILE {% endblock %}

{% block content %}
<h1 class = "pro_heading"> MY PROFILE</h1>
<hr>
<div class = "info">
    <p>Name: {{user.username}}</p>
    <p>E-mail: {{user.email}}</p>
    <h2 class="pro_recipes">My Recipes</h2>
    <div class = "my_recipes">
        <ul class = "my_recipes">
            {% for recipe in my_recipe_list %}
            <li><a href = "{% url 'blog:edit' recipe.id %}">{{recipe.recipe_name}}</a></li>
            {% endfor %}
        </ul>
    </div>
    <h3 class = "change_password">Change Password</h3>
    <div class="change_pass">
    <form action = "{% url 'blog:changepassword' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value= "Change password">
    </form>
    </div>
</div>
<script src="{% static 'blog/match.js' %}"></script>
{% endblock %}

recipeWebsite/blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}Register{% endblock %}

{% block content %}
<h1 class="reg_heading">WELCOME TO OUR TEAM!</h1>
<div class = "reg_form_big">
<form class="reg_form" action = "{% url 'blog:createuser' %}" method="POST">
    {% csrf_token %}
    <label for = "username">Username: </label>
    <input type ="text" name ="username" id="username" required>
    <label for = "email">Email: </label>
    <input type ="text" name ="email" id="email" placeholder="someone@example.ca" required>
    <label for = "id_new_password1">Password: </label>
    <input type ="password" name ="password" id="id_new_password1" required>
    <label for = "id_new_password2">Please confirm your password: </label>
    <input type ="password" name ="password_conf" id="id_new_password2" required>

    <input type = "submit" value = "Register">

</form>
</div>
<script src="{% static 'blog/match.js' %}"></script>
{% endblock %}